
default_language_version:
  python: python3.9

repos:
  - repo: git://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-merge-conflict
  - repo: https://github.com/asottile/seed-isort-config
    rev: v1.9.4
    hooks:
      - id: seed-isort-config
        language_version: python3.8
  - repo: https://github.com/timothycrosley/isort
    rev: cd9c2f6
    hooks:
      - id: isort
  - repo: https://github.com/psf/black
    rev: stable
    hooks:
      - id: black
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.770
    hooks:
      - id: mypy
        additional_dependencies:
          - "pydantic"
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.7.9
    hooks:
      - id: flake8
  - repo: https://github.com/PyCQA/bandit
    rev: "1.6.2"
    hooks:
      - id: bandit