version: "2"

tasks:
  default:
    cmds:
      - echo "No default task."
    silent: true

  start:
    cmds:
      - pipenv run python {{cookiecutter.project_slug}}/{{cookiecutter.project_slug}}.py

  bootstrap:
    cmds:
      - git init
      - brew install pipenv
      - pip3 install pre-commit
      - pre-commit install
      - pipenv install --dev
      - pipenv install pylint --dev
      - pipenv install black --dev --pre
      - pipenv install twine --dev
      - git add *
      - git commit -m "Initialized via bootstrap command in Taskfile."
      - echo "Happy hacking you glorious code weasel!"

  build_package:
    cmds:
      - pipenv run python setup.py sdist bdist_wheel
      - pipenv run twine check dist/*

  publish_package:
    cmds:
      - pipenv run twine upload dist/*

  test:
    cmds:
      - echo "No tests."
    silent: true
